### ISSUE TITLE
Lojidoc fails to install using stable rust

### ISSUE THREAD

**Issue by amgoodfellow** [JoshBrudnak/Lojidoc#16]
**Describe the bug**
Performing a `cargo install lojidoc` while the default toolchain is set to stable results in a build failure.

**To Reproduce**
`rustup default stable`
`cargo install lojidoc`

**Expected behavior**
Error-free installation

**Additional context**
It might be nice to add to the README that building the project requires the nightly toolchain.

**Comment by JoshBrudnak** [comment]
@amgoodfellow Sorry for the late response. Currently Lojidoc is able to build using the default toolchain so it could have been a temporary bug in stable. Can you check if it is still failing and if it is can you post the output? Thanks :100:

**Comment by amgoodfellow** [comment]
Ope, you're right - my bad. Everything seems to work as expected. I guess I'll close out this issue. Thanks!
