### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by JoshBrudnak** [JoshBrudnak/Lojidoc#9]
Currently lojidoc does not work on Windows due to a number of unknown bugs. We need to test it on windows and figure out where it is failing.

**Comment by Treevs** [comment]
Relating to the problem that cropped up in issue #5, I think it's struggling on the carriage return token. I added it to the lex_contents function next to ' ' and '\t' and it works for me on Windows 10.

It's an incredibly small fix, but the output looks the same on Windows 10 and OSX for the couple Java files I tested it on and I didn't see any other Windows related issues. I have a pull request ready to go if you'd like, unless there are other Windows bugs you'd like looked into.

**Comment by JoshBrudnak** [comment]
I'm not sure if that fixes all the issues on Windows but I'm definitely willing to merge in your changes. Thanks. :tada:

**Comment by JoshBrudnak** [comment]
Successfully tested on Windows, closing
